---
title: "`r params$report_title`"
author: "`r params$report_author`"
date: "`r params$report_time`"
output:
  html_document:
    toc: True
params:
  report_title: "Show transcript feature types for a single sample"
  report_author: "Anonymus"
  report_time: !r format(Sys.Date(), format="%d/%m/%Y")
  input_format: "pseudo_tab"
  input_path: "/home/rstudio/local_files/example_data/pseudo_tabular_format.csv"
  output_folder: "."
---

## Setup

```{r}
library(dplyr)
library(tidyr)
library(tibble)
```

## Parse input

```{r}
in_tab <- read.csv(params$input_path)
```

### Reshape if pseudotabular

Data might come as a pseudo-table with entities in column names. This has to be
as a minimum, reshaped to long format.

```{r}
if (params$input_format == "pseudo_tab") {
  main_tab <- in_tab %>%
    pivot_longer(everything()) %>%
    rename(Entity = name, Label = value) %>%
    dplyr::filter(!is.na(Label))
}
```


## Create distance matrix

```{r}
distmat <- dist(example_df, method="binary")
```